services:
  app:
    build: ./docker
    volumes:
      - ./app/:/var/www/html
      - ./apache/httpd.conf:/etc/httpd/conf/httpd.conf
    ports:
      - 80:80
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: mysql:8.2.0
    volumes:
      - ./db-data/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Gg62zWrT
      MYSQL_USER: laravel
      MYSQL_PASSWORD: nNi3RqmY
